### ISSUE TITLE
Issue graphing "grapher" ident.

### ISSUE THREAD

**Issue by samertm** [sourcegraph/srclib-java#23]
https://sourcegraph.com/sourcegraph/srclib-java@04f99061fff6bdf92d21fb18c6fe90544d5fbb0d/.tree/src/main/java/com/sourcegraph/javagraph/GraphCommand.java#startline=262&endline=262

"grapher" is linked to the "grapher" object and the "graph" function.

**Comment by alexsaveliev** [comment]
This issue happens when in expression `foo.bar` `foo` contains `bar`. Example: `grapher.graph()`. Supposed to be fixed by alexsaveliev/srclib-java@3e5e3fe809e6c65126d4c3cdc0badcc35e3f5524
