### ISSUE TITLE
Cross-refs not appearing correctly

### ISSUE THREAD

**Issue by rothfels** [sourcegraph/srclib-java#79]
E.g. in https://sourcegraph.com/github.com/dlew/joda-time-android/-/def/JavaArtifact/joda-time-android/library/-/net/danlew/android/joda/JodaTimeAndroid:type, you'll see `DateTimeZone.setProvider` is referenced; however, if you look at the [page for that function](https://sourcegraph.com/github.com/JodaOrg/joda-time/-/info/JavaArtifact/joda-time/joda-time/-/org/joda/time/DateTimeZone:type/setProvider:org.joda.time.tz.Provider), it does not properly show the cross reference

**Comment by alexsaveliev** [comment]
Opened ticket in Asana, I doubt it's related to Java toolchain. Moreover, cannot reproduce it on my local instance
