### ISSUE TITLE
Don't emit auto-genned symbols

### ISSUE THREAD

**Issue by rothfels** [sourcegraph/srclib-java#80]
E.g. on https://sourcegraph.com/github.com/antoniolg/RecyclerViewExtensions and https://sourcegraph.com/github.com/antoniolg/MaterializeYourApp the top symbol results all 404.

It's common for Android-based projects to have some files generated (e.g. R.java) but that are not versioned, which makes them bad search results, so we should probably just not emit them at all / filter them out.

**Comment by alexsaveliev** [comment]
Duplicates #76
